### ISSUE TITLE
Can legacyflumeoffset be removed?

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/margaret#35]
It looks so incomplete as to be nearly useless.

https://github.com/ssbc/margaret/blob/master/legacyflumeoffset/impl.go#L57-L63

For the sake of simplifying the codebase, can this module be removed?

**Comment by cryptix** [comment]
I won't die on this hill. The main idea was to be able to copy an JS log into Margaret's own format.

**Comment by cryptix** [comment]
An alternative might be to make it strictly read-only

**Comment by KyleMaas** [comment]
It's a potentially useful idea, but it just seems like an awful lot of technical debt and a lot of stale code for something that isn't fully implemented and doesn't appear to be used.

**Comment by cryptix** [comment]
yup, like I said, definitely not heart pressed on keeping this at all.

A third option might be to make an go-ssb-exp repo, where unfinished things might live for reference, similar to the junkyard org? In a similar vein, I moved an unfinished ssb-peer-invites plugin to https://git.sr.ht/~cryptix/go-exp/tree/experimental-ssb

**Comment by KyleMaas** [comment]
That sounds like a great idea for a way to handle it.

**Comment by cryptix** [comment]
Yea, might take me a few days until I get around to it but I can take care of that.

**Comment by KyleMaas** [comment]
Awesome.  Thanks!
